### ISSUE TITLE
Request for capability

### ISSUE THREAD

**Issue by suciokhan** [BirchKwok/LynseDB#8]
Thanks a lot for making this- for people on systems that aren't allowed to install C++ compilers, having a pure-Python vector database is wonderful.

I'm not seeing a means of retrieving the metadata (e.g. "fields" in the nomenclature you use in your readme example) associated with a given record at this time; for my database, I stored the original string the vector represents, in the hope of retrieving whatever string most-closely matches my query. If it's possible to do this, can you please add that to your tutorials? If it's not a feature would you please consider adding it?

Thanks again for building this cool project.

**Comment by BirchKwok** [comment]
Thank you for your constructive suggestions. It seems you are proposing to query directly by field rather than vector. Could it be that you are looking to utilize only the KV storage component of our current MinVectorDB? I am not entirely sure what your intention is; perhaps you could provide a sample to explain further?

Let me first clarify my understanding:

-  Query Method: The query is based on dict-type fields.

- Query Path: Queries are executed through the KV storage, accessing all stored fields. Your query may involve multiple keys, and it would be helpful to clarify the key matching rules. Regardless, the process will return all fields that match your query. We then extract the IDs of these matching fields and sort them based on how closely they match the field criteria, eventually returning the IDs and scores (possibly calculated as the number of all matched key-value pairs divided by the total number of keys in the query).

Looking forward to your clarification and example to better understand your approach.

**Comment by suciokhan** [comment]
Not querying for the metadata, but getting the metadata stored in a record after querying based on an input vector.

For example- I have a string "This is a blue ball". I vectorize it, and then save the vector to the database, along with the original string in a field "text":"This is a blue ball".

I then have a string I want to use to make a query vector to look for similar documents. The query string is "This is a light-blue ball". I then convert it to a vector and query the database. The database says I have a similar document...but there doesn't seem to be a way to see what that document actually says, because I don't see a way to get the fields for the matches.

**Comment by BirchKwok** [comment]
> Not querying for the metadata, but getting the metadata stored in a record after querying based on an input vector.
> 
> For example- I have a string "This is a blue ball". I vectorize it, and then save the vector to the database, along with the original string in a field "text":"This is a blue ball".
> 
> I then have a string I want to use to make a query vector to look for similar documents. The query string is "This is a light-blue ball". I then convert it to a vector and query the database. The database says I have a similar document...but there doesn't seem to be a way to see what that retrieved document's fields contain, because I don't see a way to get the fields for the matches.

Thank you very much for your clarification! This feature is already under development for the next version, as you described, it has always been on our roadmap. Currently, the project is undergoing a complete rebranding (to avoid some unnecessary issues) and performance optimization. You can expect to see the new version and the implementation of this feature soon. Please stay tuned.

**Comment by BirchKwok** [comment]
The new version already includes the search function you mentioned. Please refer to the README file for usage. Thank you. This issue has been resolved, so I will close it.
